---
# file: roles/cdh_hadoop_config/tasks/main.yml

- name:  Create config dir for hadoop
  file: path=/etc/hadoop/conf.{{ site_name|lower }} state=directory owner=root group=hadoop mode=0755
  tags:
    - create-hadoop-config
    - update-hadoop-config

- name: run 'update-alternatives' to install hadoop configuration
  command: update-alternatives --install /etc/hadoop/conf hadoop-conf /etc/hadoop/conf.{{ site_name|lower }} 50
  tags:
    - create-hadoop-config
    - update-hadoop-config

- name: run 'update-alternatives' to set hadoop configuration
  command: update-alternatives --set hadoop-conf /etc/hadoop/conf.{{ site_name|lower }}
  tags:
    - create-hadoop-config
    - update-hadoop-config

- name: configure core configs in /etc/hadoop/conf.{{ site_name|lower }}
  template: src={{ item }} dest=/etc/hadoop/conf.{{ site_name|lower }}/{{ item }} owner=hadoop group=hadoop mode=0644
  with_items:
    - configuration.xsl
    - core-site.xml
    - hadoop-policy.xml
    - hadoop-env.sh
    - log4j.properties
    - hadoop-metrics.properties
    - hadoop-metrics2.properties
    - slaves
  tags:
    - update-hadoop-core-config
    - update-hadoop-config

- name: configure hdfs configs in /etc/hadoop/conf.{{ site_name|lower }}
  template: src={{ item }} dest=/etc/hadoop/conf.{{ site_name|lower }}/{{ item }} owner=hdfs group=hdfs mode=0644
  with_items:
    - hdfs-site.xml
    - dfs.hosts.exclude
  tags:
    - update-hadoop-hdfs-config
    - update-hadoop-config

- name: configure yarn configs in /etc/hadoop/conf.{{ site_name|lower }}
  template: src={{ item }} dest=/etc/hadoop/conf.{{ site_name|lower }}/{{ item }} owner=yarn group=yarn mode=0644
  with_items:
    - yarn-site.xml
    - yarn-env.sh
    - yarn.hosts.exclude
    - fair-scheduler.xml
    - container-log4j.properties
  tags:
    - update-hadoop-yarn-config
    - update-hadoop-config

- name: configure container executor in /etc/hadoop/conf.{{ site_name|lower }}
  template: src={{ item }} dest=/etc/hadoop/conf.{{ site_name|lower }}/{{ item }} owner=root group=root mode=0600
  with_items:
    - container-executor.cfg
  tags:
    - update-hadoop-yarn-config
    - update-hadoop-config

- name: configure mapreduce configs
  template: src={{ item }} dest=/etc/hadoop/conf.{{ site_name|lower }}/{{ item }} owner=mapred group=mapred mode=0644
  with_items:
    - mapred-site.xml
    - mapred-env.sh
  tags:
    - update-hadoop-mapreduce-config
    - update-hadoop-config
