- name: Ensure group are present
  group: name={{ group }} state=present
  tags:
    - create-hadoop-user

- name: Add user {{ user }}
  user: name={{ user }} group={{ group }} state=present
  tags:
    - create-hadoop-user
