---
# file: roles/cdh_hadoop_common/tasks/main.yml

- name: install base Hadoop packages via apt
  apt: name={{ item }} update_cache=yes
  with_items:
    - hadoop-lzo
  tags: hadoop

- name: create the /data directory
  file: path=/data owner=hdfs group=hdfs state=directory
  tags: hadoop

- name: create the /data/dfs directory
  file: path=/data/dfs owner=hdfs group=hdfs state=directory
  tags: hadoop

- name: remove base Hadoop packages via apt
  apt: name={{ item }} state=absent
  with_items:
    - hadoop-lzo
  tags: remove-hadoop