---
# file: roles/cdh_hadoop_common/tasks/main.yml

- name: install base Hadoop packages via apt
  apt: name={{ item }} update_cache=yes state=present force=yes
  with_items:
    - libsnappy1
    - libsnappy-dev
    - liblzo2-2
    - liblzo2-dev
    - hadoop
    - hadoop-lzo
  tags:
    - install-hadoop-common
    - install-hadoop

- name: remove base Hadoop packages via apt
  apt: name={{ item }} state=absent
  with_items:
    - hadoop-lzo
  tags:
    - remove-hadoop-common
    - remove-hadoop