---
# file: roles/cdh_hadoop_journalnode/tasks/main.yml
# see http://touk.pl/blog/en/2012/10/30/hadoop-ha-setup/ and
# http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/HDFSHighAvailabilityWithQJM.html


- name: install hadoop-hdfs-journalnode via apt
  apt: name=hadoop-hdfs-journalnode state=present update_cache=yes force=yes
  tags:
    - install-hadoop-hdfs-journalnode
    - install-hadoop-hdfs
    - install-hadoop

- name: create the data directory for journal nodes edits
  file: path={{ item }} state=directory owner=hdfs group=hdfs mode=0700
  with_items:
    - "{{ dfs_journalnode_edits_dir }}"
  tags:
    - install-hadoop-hdfs-journalnode
    - install-hadoop-hdfs
    - install-hadoop

- name: start hadoop-hdfs-journalnode
  service: name=hadoop-hdfs-journalnode state=restarted
  tags:
    - install-hadoop-hdfs-journalnode
    - start-hadoop-hdfs-journalnode
    - start-hadoop-hdfs
    - start-hadoop

- name: stop hadoop-hdfs-journalnode
  service: name=hadoop-hdfs-journalnode state=stopped
  tags:
    - stop-hadoop-hdfs-journalnode
    - stop-hadoop-hdfs
    - stop-hadoop

- name: remove hadoop-hdfs-journalnode via apt
  apt: name=hadoop-hdfs-journalnode state=absent purge=yes
  tags:
    - remove-hadoop-hdfs-journalnode
    - remove-hadoop-hdfs
    - remove-hadoop

- name: configure rsyslog for hadoop-hdfs-journalnode
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hadoop-hdfs-journalnode.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog
